### ISSUE TITLE
Publish Rust Extension Pack to Open VSX

### ISSUE THREAD

**Issue by tigsikram** [swellaby/vscode-rust-pack#117]
Dear extension author,
Please publish this extension to the Open VSX marketplace.

## Context

Unfortunately, as Microsoft prohibits usages of the Microsoft marketplace by any other products or redistribution of `.vsix` files from it, in order to use VS Code extensions in non-Microsoft products, we kindly ask that you take ownership of the VS Code extension namespace in [Open VSX](https://open-vsx.org/) and publish this extension on Open VSX.

## What is Open VSX? Why does it exist?

Open VSX is a vendor neutral alternative to the MS marketplace used by most other derivatives of VS Code like [VSCodium](https://vscodium.com/), [Gitpod](https://www.gitpod.io), [OpenVSCode](https://github.com/gitpod-io/openvscode-server), [Theia](https://theia-ide.org/)-based IDEs, and so on.

You can read on about Open VSX at the Eclipse Foundation's [Open VSX FAQ](https://www.eclipse.org/legal/open-vsx-registry-faq/).

## How can you publish to Open VSX?

The docs to publish an extension can be found [here](https://github.com/eclipse/openvsx/wiki/Publishing-Extensions). This process is straightforward and shouldn't take too long. Essentially, you need an authentication token and to execute the `ovsx publish` command to publish your extension. There's also [a doc](https://github.com/open-vsx/publish-extensions/blob/master/docs/direct_publish_setup.md) explaining the whole process with an example GitHub Action workflow.

## On a personal note…

I use VSCodium on Linux and would love to see this extension pack on Open VSX. I have done my homework, though: you've already [attempted this](https://github.com/EclipseFdn/open-vsx.org/issues/649) for vscode-rust-test-adapter two years ago. Has your [opinion](https://github.com/EclipseFdn/open-vsx.org/issues/649#issuecomment-920541002) on the needlessly invasive permissions changed? I just checked: open-vsx.org still requests `read:user`. If OVSX uses OAuth only for authentication, this must simply be an unfortunate configuration error, as “read-only access to public information (including user profile info, repository info, and gists)” [is available without scope](https://docs.github.com/apps/oauth-apps/building-oauth-apps/scopes-for-oauth-apps#available-scopes).

If the sloppy permission management is the only major concern, you could try removing the `scope`-parameter from the `github.com/login/oauth/authorize`-URL when trying to log in to open-vsx.org.

Let me know how you'd like to proceed, for now I'm installing the VSIX manually.

**Comment by calebcartwright** [comment]
Thanks for the request, and I appreciate the accompanying homework 😄 

However, I don't plan to pursue trying to work with OVSX again at this time nor for the foreseeable future. As noted your request already linked some of my previous commentary on the matter, and I'll also add in https://github.com/swellaby/vscode-rust-test-adapter/issues/94 more directly to highlight some of the challenges and time lost trying to do so in the past.

The best place to get this extension outside of Microsoft's marketplace is the [releases in this repository](https://github.com/swellaby/vscode-rust-pack/releases)
