### ISSUE TITLE
Rust Analyzer

### ISSUE THREAD

**Issue by calebcartwright** [swellaby/vscode-rust-pack#23]
## Extension Info

* **Extension Name**: rust-analyzer
* **Link to Extension on Marketplace**: https://marketplace.visualstudio.com/items?itemName=matklad.rust-analyzer
* **Are there similar Extensions?**:   yes, alternative to the main RLS extension

## Value

I've not used this one yet, but is supposed to have solved some of the problems currently experienced with the RLS extension. Mostly opening this for exploratory/research, though if anyone has any experience thoughts please share!

**Comment by calebcartwright** [comment]
Probably going to wait a bit longer on this to see how the RLS/RA extension structure plays out to avoid having to change this twice

**Comment by Zerotask** [comment]
I'd stick with the the official Rust extension, since they are very similar in case of features.

Regarding static code analysis there is also an official Rust project called [Clippy](https://github.com/rust-lang/rust-clippy). I didn't find a VSCode extension about it. Having this installed with an extension could be really beneficial.
> A collection of lints to catch common mistakes and improve your Rust code.
> There are over 400 lints included in this crate!

**Comment by calebcartwright** [comment]
> I'd stick with the the official Rust extension, since they are very similar in terms of features.

RA is very much an official project; it's also known by its other name of RLS 2.0. It was originally released as a separate extension, but is ultimately (at least most likely) going to be made available as an engine within the current VSC extension.

RLS itself is _largely_ in maintenance mode and the RA is used very widely, but also want to avoid shuffling back and forth between extensions

**Comment by Zerotask** [comment]
Thanks for poiting that out. I didn't know that, but now I'll install it and give it a try.

**Comment by TDiblik** [comment]
Hi, +1 here for rust-analyzer. 

If you look at the [commit history of the official Rust package](https://github.com/rust-lang/vscode-rust/commits/master), you'll see that it's not really maintained, considering how many open issues are opened at the moment (around 200), but there wasn't any commit to master for nearly a year!

Now take a look at the [realease cycles](https://github.com/rust-analyzer/rust-analyzer/releases) and [commits](https://github.com/rust-analyzer/rust-analyzer/commits/master) in the rust-analyzer repo. Yes, there are A LOT more opened issues (around 900 rn), but I would still suggest to replace it now or in the near future.

Personally, I find the rust-analyzer a little bit harder to setup as I've had some issues with it, but as far as the functionality goes, it's a lot better. Also, isn't it now supported by mozila as said in their's README?
![image](https://user-images.githubusercontent.com/71404604/149637121-e001bc02-a8ab-4027-9665-22639cc8878d.png)

**Comment by calebcartwright** [comment]
Thanks for sharing your perspective @TDiblik, but it's not really a question of activity. 

There's two related, but separate, considerations still underway: RA vs RLS as the LSP, and the VS Code extension(s) on the marketplace. I'd encourage those interested in more details/status to take a look at https://github.com/rust-lang/vscode-rust/issues/812 (and associated linked issues, zulip threads, etc.)

Obviously for the former the plan is for RA to replace RLS as the official language server at some point, but that still has some things that need to be sorted, and until then RLS is technically still the official one (even though most folks have indeed already switched to RA)

The latter consideration has less clarity, but I which I believe will result in an end state that's something other than the current RA extension namespace. I'm not keen on changing the extension pack today and then having to make a similarly substantial change yet again down the road, so this is largely blocked on the resolution of upstream plans.

**Comment by calebcartwright** [comment]
Just in case anyone's tracking this, there's been good movement upstream and RA is officially joining the Rust organization as many probably saw in the recent blog posts. There's still a few final pieces being discussed, including details like the name/publisher for the new branding of the RA extension on the marketplace (and all signs are pointing to it being something different than the current two, likely rust-lang.rust-analyzer).

Once that's all sorted we'll make the corresponding update here in short order
