### ISSUE TITLE
Replace "Better TOML" with "Even Better TOML"

### ISSUE THREAD

**Issue by Zerotask** [swellaby/vscode-rust-pack#35]
Even Better TOML provides more features, is more up to date and has a better marketplace rating (5 stars compared to 3 stars from Better TOML).

Better TOML last commit was Jul 5, 2019, so it's probably not really maintained anymore.

Even Better TOML Links:
https://marketplace.visualstudio.com/items?itemName=tamasfe.even-better-toml
https://github.com/tamasfe/taplo

![image](https://user-images.githubusercontent.com/20150243/111840794-43c4b380-88fd-11eb-8690-3b071cca0831.png)

**Comment by nikitalita** [comment]
Please, Better TOML has been broken on newer cargo versions that are using the newer TOML crate for a while now.

**Comment by calebcartwright** [comment]
> Please merge this

Worth noting this is the issue, not the PR :wink: 

> Better TOML has been broken on newer cargo versions that are using the newer TOML crate for a while now.

Can you elaborate or better explain what you mean by this? I.e. which newer versions of cargo, what exactly is broken, and how does the version of cargo or the utilized toolchain more generally relate to a TOML extension in an editor?

While I fully anticipate we'll make this change, as I've noted in the linked PR, I'm not aware of any issues that exist with the current TOML extension nor have I seen any myself in the usual suspects of TOML files in the Rust ecosystem (Cargo.toml, rustfmt.toml, new rustup toolchain file, etc.)

**Comment by dani162** [comment]
Better TOML does not work for the new `workspace inheritance`, [Even Better TOML](https://marketplace.visualstudio.com/items?itemName=tamasfe.even-better-toml) seems to work
https://blog.rust-lang.org/2022/09/22/Rust-1.64.0.html#cargo-improvements-workspace-inheritance-and-multi-target-builds
https://doc.rust-lang.org/cargo/reference/workspaces.html#the-package-table

**Comment by slhmy** [comment]
🫥 I'm pretty annoying to have my VS Code noticing me to change toml extension every time.

But the PR in this issue seems to be rarely old I think (it's 2 years ago)?
If possible I'll try to start from the linked PR and fix this issue.

**Comment by nikitalita** [comment]
<img width="790" alt="image" src="https://github.com/swellaby/vscode-rust-pack/assets/69168929/10095e10-9508-4a75-abaa-778aa48b10d7">

It's been two years since the PR was opened, and now Better TOML is EXPLICITLY marked as deprecated.

**Comment by calebcartwright** [comment]
@nikitalita - the PR was also **closed** by the author 2 years ago with no comment nor response to a question. If you or @slhmy or anyone else wants to open a PR then I'll be happy to work on getting it released.

However, posting comments here relative to the status or taking action on a closed PR isn't going to change anything.
