### ISSUE TITLE
Improve Developer Experience

### ISSUE THREAD

**Issue by Zerotask** [swellaby/vscode-rust-pack#39]
The current extension pack offers a solid foundation for Rust developers and perhaps this extension pack shouldn't be bloated up with additional extensions.

We should think about what every or most Rust developers need or have in common regarding their development process. For that we could look at other popular language extension packs and see what they have in common. But also think which tool from the Rust ecosystem would increase the productivity.

### Java Extension Pack
![image](https://user-images.githubusercontent.com/20150243/111865597-558f7080-8968-11eb-8343-7c30b4e05d98.png)

### Python Extension Pack
![image](https://user-images.githubusercontent.com/20150243/111865614-69d36d80-8968-11eb-9c8a-d6980b39f38c.png)

### C/C++ Extension Pack
![image](https://user-images.githubusercontent.com/20150243/111865687-b6b74400-8968-11eb-9690-95e9fa46d7f5.png)

### Go Extension Pack
![image](https://user-images.githubusercontent.com/20150243/111865694-c8005080-8968-11eb-93e9-378325450558.png)

### .NET Core Extension Pack
![image](https://user-images.githubusercontent.com/20150243/111865799-668cb180-8969-11eb-970f-430b72f2bebd.png)
![image](https://user-images.githubusercontent.com/20150243/111865808-71dfdd00-8969-11eb-942d-8b331c21c496.png)

## Conclusion
This conclusion is about the previous mentioned extension packs + other smaller or framework specific extension packs I found.

- Some provide an extension for testing. This was also suggested here: #9
- Some extensions add something about documentation, to allow to lookup things more easily. A possible extension could be https://marketplace.visualstudio.com/items?itemName=JScearcy.rust-doc-viewer
- Some provide extensions to improve the debugging possibilities. This was also suggested here #16 
- Some provide better support for their package manager (e. g. auto-format, tasks). A possible extension could be https://marketplace.visualstudio.com/items?itemName=panicbit.cargo
- Most / every provide Snippets. The default Rust extension does already provide snippets. We could investigate if they are sufficient.

**Comment by Zerotask** [comment]
Other (small) interesting extensions:
- https://marketplace.visualstudio.com/items?itemName=PolyMeilex.rust-targets
- https://marketplace.visualstudio.com/items?itemName=ZhangYue.rust-mod-generator

**Comment by calebcartwright** [comment]
> The current extension pack offers a solid foundation for Rust developers and perhaps this extension pack shouldn't be bloated up with additional extensions.
> 
> We should think about what every or most Rust developers need or have in common regarding their development process. For that we could look at other popular language extension packs and see what they have in common. But also think which tool from the Rust ecosystem would increase the productivity.

hi, thanks for sharing your perspective. I think this line from the top of the readme best conveys our approach to how we structure our foundational language/env-specific extension packs:

> Minimalist VS Code Extension Pack for Rust development.

It's very much intended to be minimalist, with an explicit goal of not containing anything that any of us as the maintainers would ever need to _disable_, and striving to ensure that can generally be true for a majority of consumers as well. We want the pack to only contain the subset of extensions that are non-controversial and so foundational/critical that they almost seem boring :smile: 

One of the (many) things I love about the VS Code ecosystem is how extensible it is and how easy it is to publish extensions. Anyone interested in more of a kitchen-sink style extension pack, can create their own, and even include _this_ extension pack in theirs as a building block!

As noted in your previous comments some of the ones you listed are already under consideration (e.g. #9 and #16) but the others do not clear the threshold of being unequivocally necessary in just about every situation, so I'm going to close this issue.

For reference, as the authors of the [Rust Test Explorer extension](https://marketplace.visualstudio.com/items?itemName=swellaby.vscode-rust-test-adapter) discussed in #9, we're obviously fans and proponents, but even that one is a tough sell to include here for a few reasons (for example I don't want to have it enabled/have to turn it off on the occasions when I'm working on the rustc codebase). Similarly with the debuggers, VS Code still does not support conditional nor platform specific extension recommendations to the best of my knowledge. However, two very different extensions are needed for debugging depending on whether you are on Linux/Mac or Windows using the default MSVC toolchain, and we don't want to have extensions in the pack that would be unusable/unnecessary and/or duplicative, nor would we want to only support one type of env vs. the other.
